run_as shiny;

preserve_logs true;
sanitize_errors false;
disable_protocols xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile;

server {
  listen 3838;

  location / {
    app_dir /srv/shiny-server/EcoPlots;
    log_dir /var/log/shiny-server;
    app_idle_timeout 0;
    app_init_timeout 120;
    reconnect true;
  }
}
